### ISSUE TITLE
Can't find custom attr constructor image

### ISSUE THREAD

**Issue by eridal** [atom/grunt-atom-shell-installer#123]
Hey all,

I'm getting this error. I was able to build in the past weeks, but seems something changed.
I have removed the `node_modules` folder and npm installed again, but keeps saying the same.

Does it looks like a missing external dependency?

```
Warning: Failed with exit code: null
Output:
Can't find custom attr constructor image: [redacted]/node_modules/electron-winstaller/vendor/nuget.exe mtoken: 0x0a000a76
Unhandled loader error: 8, (null) System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (null)
* Assertion: should not be reached at loader.c:298

Stacktrace:


Native stacktrace:

    mono() [0x49ff2f]
    /lib/x86_64-linux-gnu/libpthread.so.0(+0x113d0) [0x7fcd1e74a3d0]
    /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38) [0x7fcd1e3a5418]
    /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7fcd1e3a701a]
    mono() [0x630409]
    mono() [0x63069c]
    mono() [0x630833]
    mono() [0x54357a]
    mono(mono_class_from_typeref_checked+0x223) [0x524c63]
    mono() [0x5234ad]
    mono(mono_metadata_parse_mh_full+0x497) [0x5620b7]
    mono() [0x433fd6]
    mono() [0x500b39]
    mono() [0x501fbd]
    mono() [0x425db6]
    mono() [0x426749]
    mono(mono_runtime_invoke+0x3d) [0x5ac68d]
    mono(mono_runtime_exec_main+0x10d) [0x5aea1d]
    mono(mono_main+0x1177) [0x476967]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fcd1e390830]
    mono(_start+0x29) [0x422e79]

Debug info from gdb:

[New LWP 16929]
[New LWP 16928]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fcd1e749fbb in __waitpid (pid=16930, stat_loc=0x7ffec5e97e7c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
29  ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id         Frame 
* 1    Thread 0x7fcd1f268780 (LWP 16919) "mono" 0x00007fcd1e749fbb in __waitpid (pid=16930, stat_loc=0x7ffec5e97e7c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
  2    Thread 0x7fcd1b715700 (LWP 16929) "Finalizer" 0x00007fcd1e748867 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x956820) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  3    Thread 0x7fcd1d7ff700 (LWP 16928) "mono" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185

Thread 3 (Thread 0x7fcd1d7ff700 (LWP 16928)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00000000005fdcdb in ?? ()
#2  0x00007fcd1e7406fa in start_thread (arg=0x7fcd1d7ff700) at pthread_create.c:333
#3  0x00007fcd1e476b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7fcd1b715700 (LWP 16929)):
#0  0x00007fcd1e748867 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x956820) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x956820, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007fcd1e748914 in __new_sem_wait_slow (sem=0x956820, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007fcd1e7489ba in __new_sem_wait (sem=<optimized out>) at sem_wait.c:29
#4  0x0000000000622e06 in mono_sem_wait ()
#5  0x00000000005a5742 in ?? ()
#6  0x0000000000587b2b in ?? ()
#7  0x0000000000629a8c in ?? ()
#8  0x00007fcd1e7406fa in start_thread (arg=0x7fcd1b715700) at pthread_create.c:333
#9  0x00007fcd1e476b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7fcd1f268780 (LWP 16919)):
#0  0x00007fcd1e749fbb in __waitpid (pid=16930, stat_loc=0x7ffec5e97e7c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00000000004a0006 in ?? ()
#2  <signal handler called>
#3  0x00007fcd1e3a5418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#4  0x00007fcd1e3a701a in __GI_abort () at abort.c:89
#5  0x0000000000630409 in ?? ()
#6  0x000000000063069c in ?? ()
#7  0x0000000000630833 in ?? ()
#8  0x000000000054357a in ?? ()
#9  0x0000000000524c63 in mono_class_from_typeref_checked ()
#10 0x00000000005234ad in ?? ()
#11 0x00000000005620b7 in mono_metadata_parse_mh_full ()
#12 0x0000000000433fd6 in ?? ()
#13 0x0000000000500b39 in ?? ()
#14 0x0000000000501fbd in ?? ()
#15 0x0000000000425db6 in ?? ()
#16 0x0000000000426749 in ?? ()
#17 0x00000000005ac68d in mono_runtime_invoke ()
#18 0x00000000005aea1d in mono_runtime_exec_main ()
#19 0x0000000000476967 in mono_main ()
#20 0x00007fcd1e390830 in __libc_start_main (main=0x422be0, argc=9, argv=0x7ffec5e99d38, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffec5e99d28) at ../csu/libc-start.c:291
#21 0x0000000000422e79 in _start ()

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

 Use --force to continue.

Aborted due to warnings.
```

**Comment by eridal** [comment]
I am able to reproduce this by simply doing:

``` bash
mono ./node_modules/electron-winstaller/vendor/nuget.exe
```

Any pointers will be greatly appreciated.

**Comment by AhmadIbrahiim** [comment]
Hi @eridal ,

I know it's too old for this. But can you remember how you managed to solve this ?
